/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pokemon API
 * API for retrieving Pokemon data
 * OpenAPI spec version: 1.0.0
 */

export interface Pokemon {
  name?: string;
  type?: string;
  level?: number;
}
