/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pokemon API
 * API for retrieving Pokemon data
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import {
  faker
} from '@faker-js/faker'

export const getGetPokemonMock = () => (Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({name: faker.helpers.arrayElement([faker.random.word(), undefined]), type: faker.helpers.arrayElement([faker.random.word(), undefined]), level: faker.helpers.arrayElement([faker.datatype.number({min: undefined, max: undefined}), undefined])})))

export const getPokemonAPIMSW = () => [
rest.get('*/pokemon', (_req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetPokemonMock()),
        )
      }),]
